name: Core Benchmarks

on:
  push:
    branches:
      - master
  pull_request:
    types: [ synchronize, labeled ]
    branches:
      - master
  workflow_dispatch:

jobs:
  pr-summary:
    name: Create benchmark summary for a pull request
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ownership (Github Actions workaround)
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Get baseline benchmarks results
        uses: actions/cache@v4
        env:
          cache-name: benchmark-results
        with:
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.event.pull_request.base.sha }}
          path: |
            perf_benchmark.json
            synth-benchmark-basic.json
            synth-benchmark-full.json

      - name: Save PR number
        env:
          PR_NUMBER: 
        run: |
          mkdir -p ./summary
          echo ${{ github.event.number }} > ./summary/pr_number

      - name: Create comment
        id: createComment
        run: |
          . venv/bin/activate
          {
            echo "## Benchmarks summary"
            echo "### Performance benchmarks"
            echo "You can view all the metrics [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
            echo
          } >> summary/comment.md

      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-summary
          path: summary

